version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    assignees:
      - "valentjn"
    labels:
      - "pr-dependabot 🤖"
