language: java
dist: trusty
sudo: false
jdk:
- oraclejdk8
node_js:
- node
install:
- npm install
- npm install vsce
- "./lib/languagetool-languageserver/gradlew --project-dir ./lib/languagetool-languageserver/
  assemble"
script:
- vsce package
deploy:
  provider: releases
  api_key:
    secure: mIM7HSzdRYW5Mk1etYnC+O2JQbqwl7eOsaYhIQ3i657VpfsQTnvvvmYIR2MXzxOsMY713QN8npr6k2X6NRffzIcyuPw+6OJd3Q+UfYKCLCZZyPJmyu/ItXQMoGC9PPjh0jTLEI/oXd1Eb+uIhCgd1z1vrxsW5SLNL9bpSvfXRk6JkEJENKF088Fr+/H3SdMkG+ndsT8KcVbNxjYpXZisd0twFPiuI9hNy2vJJ7AgDKIZqGRjdU+VS2o+VaKFqU1cF19EUhm6+RPDbUSj4Oe5w9jn0jW9//MZwkyv6T8yjBDwRbimar3fFx6ZEy8ZVG2N1DPpDIW6hik+anBa0qGQQKQ3Obo0wgD7VG5qCJvVjKl6f4OP7l5f/ft5hvUQ1sFChXAeXWD04N3ORnlNnTjVPCJErBj065IRRPbb79WRY5JGQN0sT2iyvoOId/u5uizRrtbWKJ70DpGu1o3Hok0YT8GSIreCD1C/MHAKJ/vn/c2Q+hx2Ku3DJ3bZrhubtirpboCChlL7oeOIGp0U8LmY95UF5bdFy/wuiy/Lxb7cLwuMz7wyUAxRqZY1uduB+AdhTHEHKnzpSf9UR2uRxSclJn+CggYn88RYjB4ARmeUNeDRr40BfwKM627DiNx9qzPEJiemvkZxyIBZzZbsDwytHDkWQKQSasyy8ochODxKZsY=
  file: vscode-languagetool-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- vsce publish -p $VSCE_TOKEN
env:
  global:
    secure: CnLZvbTTk4NGIs5GsBndlcLxbqIC2jDO4zQ3io/YvUS3Ez7feH4x3mn3RZNYBiaJtL63VVg0y9LE4diQXXCNegR2CxYy4/dH9pbyDR3FmpCwFFL7p5GuBklyRk9Zu6td4x9f32WaIRizH9gCaCwHc8QcxuXLk/nOAf+80VWMlEmGA6ds89vlmQi6MIKG+t33P+z7u9f9LEZ64nuTeru6SIGCcQPDUnOIwkFLLRXhmN2CTeL7mI0dMu1T5hSgOHxFyCh9uyh2E9Hpq4kDc6SkOupTWSOgNVRDDD1MeDsgEZKWm0Anyb9Soi3ePN+csGN/K9QNTmA6+gtDLayp7ufQhr4D6SDYRzGm5ytT3q1yvo2rOkSHVm/0J9HH2370Oyx1YFJe3H/GtR0WccJ29gETNPZ1UBWk4wWcWOeRiDLWXyxClQ4U6XRxc7cCRjqYP5raPB55eeE2/afKQVkhn3TXFJO9elaQ4/rXmV+TYUKjna0K7K9aKVUbzLdGp3s/6FaruJ3j1YUJ3Gw3seqthaJxjLxpCLQS/lBvex30HsZNrHI2myd8lziDb3XPEHOnhXZAQLFNyCfBY01RAEfOSrstl9fhMp4PnQZkn8ieCY7pRYZ03up32B3o9DOUKQUVtbgNa9Y6T2r4mPf2lhZQNgdnViSblu3z2ArrM0uodrmm8lI=
