language: java
dist: bionic
jdk:
- oraclejdk11
node_js:
- node
install:
- npm install
- npm install -g vsce
- "./lib/languagetool-languageserver/gradlew --project-dir ./lib/languagetool-languageserver/
  assemble"
script:
- "vsce package"
deploy:
  provider: releases
  api_key:
    secure: eADqNMr3tbUsCyKWeAPJeqlBm+vdnYDZ0Cqj8+Fu+DJs4vnNvubNGjvA/MYFRDtliRAUVRdtxwwex4Qs4ETxq4SboZCpDKFYjlGtNvKiB71YNHP4lGrhPkV1PNlva+SWVpWfyuRaaqPkUKzuV6MkfBCUtLa9x2DZF3xL5hRBEd23WnuBi7x8WZLaMAQoX4fOLA0q/AXHaWmjOab1O7dhrmJ+LW+W3Eu+6DLkQYOGe6PzkdlDRxa1m/U9mlJSLqCOJkQlnjIlzLWpN+XoxXv+d2/wAfXZLDnHRaV6WGGQ0sa3hM1KqqTaLIQQsRAh1Hv0+lfA5pQduZXsou9ZX5lndXsPybYMLfJGWuqp0FvlGBz4I9yMCGRQcMvb/6AqMjrFRRYvJ/WElFq9+Ff7ivPRW2OETNnLVVaUA7QPs4oQSc8HpMxebsnV8lQYIXnu5g67/2Ua1zXTmILq29v8tpQDY4+vRIGNL0Li6F421fxwNqiRmK/tPLo1Qpvt4MxtUC1gSvMErCDo0D59XL/fB+6k0E/jx/BjTKjedNyXqs2xikLJQbR9kMrgWUE2t9KSAw5J+GhqMTDme0CBGINnbEwxOx6iGIcUzvSY1Hy2uZb8aaAc9OFwQKIK8MHXliIOu325Hj5UnQANbadpuP1UKT0+38FrqYk5dSRQTi9+eb3NFvY=
  file: vscode-ltex-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    repo: valentjn/vscode-ltex
    tags: true
after_deploy:
- "vsce publish -p $VSCE_TOKEN"
env:
  global:
    secure: FqSrXLIaTMkyCOTErkr0qKXPs6cKCd+1X7Ctj9lpsdDcTSzyfx/E5NsmOs/rejA0Qd6kKQ6ulZqAU0Z6yDarUp8n+vE0wZ4dz6Zo0xclSIVR+sTBD3aRussz1fI4nHLkCtSuKNiBaUM3tLz8VQtqJLVaW1eyGnoA0+HbCpV28tSVRlurArguLkDo2cPXiSRqGkU5iTXUrsZihDej/4GIsfEotH+keqHNb1SJclMTe5TNjQobU3B2ssOlnPtQeBizkiaSroLRmJGzk7muJDotai6r6Ac/UQ4momAReUho3NadqzDr0XE3Fn47sE3rrggYSZ8xDl0fc5pZJ/w+3+MXVHYjuWXYFX3PvtinZLXiJCr8UFMxpsYbcvdlb3zkqYwpRVGhZ3zGLdQ72E8PHuwNsS3kjD0uNd/L7LhNEEZicoIHkqRgXqnxHYOvTOB7zaWB/3FBz0PMI1EpzhoyrjJi6LwcMnM6jq+RMEgJeR0SSqzt+hE8TP6IHwBVKzNMO1H63MpkFc8OR3FU/XlxgJzc144zjRxoTlrK1i38Pszh4gShReJ0WD0psUhxsBhio8nCZp+YlQGTmam0j7FohnqUMk5WWLIaRy8IBslTPdu6JOR+jlrrQ4acnaj3Zr4wMucrkM5NMFKgrQtc3KaHZ7M7RPX5pvk5IKWThH5/EbOZ8cM=
