# Copyright (C) 2020 Julian Valentin, LTeX Development Community
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

os: "linux"
dist: "bionic"
language: "node_js"
node_js: "13"
cache: false
stages:
  - "test"
  - "deploy"
install: &commonInstall
  - "npm install"
  - "npm install -g vsce@1.79.3 ovsx@0.1.0-next.bcce4bc"
script: &commonScript
  - "vsce package"
jobs:
  include:
    - stage: "test"
      os: "linux"
      install:
        - *commonInstall
        - "sudo apt-get -y install python3-pip"
        - "pip3 install semver"
        - "export DISPLAY=':99.0'"
        - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
      script: &testCommonScript
        - *commonScript
        - "npm run lint"
        # to suppress "async hook stack has become corrupted" errors
        # (https://github.com/microsoft/vscode/issues/85601)
        - "export NODE_OPTIONS='--no-force-async-hooks-checks'"
        - "npm run test"
    # deactivated due to similar phenomenon as described in a8d0fe9f19
    #- stage: "test"
    #  os: "osx"
    #  install:
    #    - *commonInstall
    #    - "pip3 install semver"
    #  script:
    #    - *testCommonScript
    # deactivated due to https://github.com/microsoft/vscode/issues/77499
    #- stage: "test"
    #  os: "windows"
    - stage: "deploy"
      if: "tag IS present"
      install:
        - *commonInstall
        - "sudo apt-get -y install python3-pip"
        - "pip3 install semver"
      script:
        - *commonScript
        - "export LTEX_LS_VERSION=\"$(python3 -c \"import json; print(json.load(open('package.json', 'r'))['version'], end='')\")\""
        - "if [[ -z \"$LTEX_LS_VERSION\" ]]; then echo 'Error: LTEX_LS_VERSION not set!'; (exit 1); fi"
        - "export IS_PRERELEASE=\"$(python3 -c \"import semver; print('1' if semver.VersionInfo.parse('$LTEX_LS_VERSION').prerelease is not None else '0', end='')\")\""
        - "if [[ -z \"$IS_PRERELEASE\" ]]; then echo 'Error: IS_PRERELEASE not set!'; (exit 1); fi"
        - "if [[ \"$IS_PRERELEASE\" -eq \"0\" ]]; then echo 'Detected stable release.'; else echo 'Detected prerelease.'; fi"
      before_deploy: "python3 tools/createOfflinePackages.py"
      deploy:
        - &deployBlock
          provider: "releases"
          token:
            secure: "AHYqCvN9tkw2qxP8AtVWbTh+G7IKHJXrCFOsYSQA5etxVDGACdk6uMA2Lp6DEkb2rUVsn/6FKWCkDL91PzMVrAzuQ95A4OpSM2edWjgZk/y0BEcldImOg/N0ekcSltRKS2IA7vY6slcsrGKLfmWt/dCxA7U5ddYp3iOJHv89POZck+F0y9W9U2bvsbvi4g9+Kjd+8dwHATz/OiiEBh9FfKMJ7TG27tnQ67wLFp0rYptCDTjQd3sISApdXhy4dFo8D4aZfHnZICZ61cYiEf1F4OypmjhQe5/w7BexEl0VOC26OJQ//W17r9kVavi+d7HiGsAtzJ4ftJTLCrHAZRkc/L4QRBZ95LJAsbp9WgcZZfAljlub+xCC9t+jCzS/OVPRxZfr4nGRNXGfjcVf67LtDAYQXICrgDKqIIm/PtxUGTs6vsVI13FD6HX7F/6pLCJqjGwDWNyezn4vJLMS+/Q6X+ytGl1Vv0zv7mvL0LdhZ/OKQwSC/5YKeQPcJUSZijKgVpLoaX8ZQXlOBwZGS0IG14y0M5Mu+hr1rTT/k0OIplMIBtJMQ0TbfCUbXuhZJLK3ZUGt3v0ptuy27+cy7NV9pWtjlEMHAovv+1RP4TApnD+AR1YHhtA5KEvbGoeTKg/yE5C4KrHEsObedx9RVG2BFkYXWymjvlMtxMR0SnR5uw0="
          file: "vscode-ltex-*.vsix"
          file_glob: true
          # needs to be removed for Travis's dpl v2
          # see https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#cleaning-up-the-git-working-directory
          skip_cleanup: true
          on:
            repo: "valentjn/vscode-ltex"
            tags: true
            condition: "\"$IS_PRERELEASE\" -eq \"0\""
        - <<: *deployBlock
          prerelease: true
          on:
            repo: "valentjn/vscode-ltex"
            tags: true
            condition: "\"$IS_PRERELEASE\" -eq \"1\""
      after_deploy: "if [[ \"$IS_PRERELEASE\" -eq \"0\" ]]; then vsce publish -p $VSCE_TOKEN; ovsx publish -p $OVSX_TOKEN; fi"
env:
  global:
    # LTEX_GITHUB_OAUTH_TOKEN
    - secure: "QItpkca5Ivww87eeBJmaixRBb/7O6WYafVVRAzbRxlDupZZQTddF6psza3rdekxIIw4yudDlW3qUEdTG4eN17ZGWZHUumYpw2d8XlmGYXseVgM5nQLpa8hTsKea41dp9STOjyK1EqH8qpX9EihQEp92yqlyJD3qgZFFFqmAe5ws3VhFc+CEEqew5UAgoDuB34j++sMWqfVS3+ep/9778Rtb/3F8xFk/oytZHixEcu+SvMDxidv9bw8QROI24kzWRLz/oaH8BW3XuVn0BquW0NdqLoOsn3vjErN6AunTVIkOTl0MhVrpnlNhGRPNeq9ujObFSv7Jt9qW6o1oWoI+EbExQpdZsHfwch+7SawuuhyZNn0IZI4RH1/U+DuyXhUOg3Gskl9Ba7eqGNJ6bqMramtuGXY7cr/gWElnD3CSqfptODNLBVz1oYfzba9j5QO8tU7y7cicYDmqm/OVq6PFHkljoSvTkuXt2CKnmhFqq17qEbuqfjqnKNFDyUNIZKGyMWe3BME5WmYA6PTC9h/soe/6NYio6p800y74gYYPVbQBHY5wXx6FVG1YKqoRKEweV2hAq0IDa2/tjF1psCkQaddvmRvQIs/52PmPkqyzRXaRJdB3Devy1keRiicmvMi4tJH30yVaay6n+HJ6u7es0CpYdn+7TPRrnOUk9//PK61o="
    # VSCE_TOKEN
    - secure: "nWRmuOXHIasLh5BaaxOgnkXXPPJ/mmBSA48fDDe8+uJ7lFUjusQvLXdfzwhoSFoebJw4w84BAAp5sV6HvhN+x9PyWBE81+HBoqmR3ao4Z+mWMKvCBLkEEWgj1xFqzlTSB6Qs6CpAFBMU1APwgN+Plg2tXVydf5M7bbtlL8MCvjSz9F6Cn1ZsQrKLCx8/ttWEJOIz1mS0FPobybChohqEFq/emmgaNZ6NcWCtH1UJvCEGPS4JXsMdGL3LqVIL0dV0tbd7G1fykmfe7lP6HIRpaLYuP9Rrhym21qJgTd0SD12in+j5x2nm2ircgbSz4Ez1enPRlyROPq7W8g5ZVdXYHNpepiRqsd+gOG1ZLYI54/zklbj3xqbwLDwQ4M+tNhodTQoaedHWM45A+X/KQlUGMyFzzc0swgNaCHnr48zjNjQQBNFxHCTUUBm0G3lp/3CpY5Y4kX/J1qdRnPBobOnLzZ0bX7QzoGI0MMZlIieHRvmC2SbSX7jRIDmnBro5pxp8cwCiNrR2tUMzC9kW361HjT0/bUZJovwTmdG968TOG5oOhSiPiwiALKAdKY4hifzccPI+h9O+TwN00QZAvReJd8yGIJ2KRCpyqDXnY7RPR/Wor/jna0DakdcM1OclzVrxbYRqhWGDa87o367Qx1rQonqPR00+K1SKlycZp8RBpw8="
    # OVSX_TOKEN
    - secure: "QyuxBgZyF0ZFKtY/lblDVc0L/KFY7cuKGomRZYseTO1CQKbb5gwFASvne2+CpaEvdTs1aNhe2I4DNe9zUGWa0OD6b8wYF2nLryesq26ruURjl0eeh+FcmJZ4omDWO80gyRS/PbeGgSDnuN9GU4Xk52cKPnkIGhOj0rdZftJyI8aapfvtmYzcUhWkJQgaRMA+kpV96ROpdm/YTcSai+qUxAHH4J9rw4EHOO/9w8yqgRQIzDYYt2ApdBYxGRSd/YalSratIlAmPy6NRhLn2acKSGd1V9BSpWeTNZatolyZEPZIcSfjI/N0vF6xquw79jNnz5SKb9q6cX9Zbh0JkIBMPRN4BakbeU6ApOLjZBo7nXboY2PzaxrXncbIsvh2yyqVrg5SVq0BTCWAfrpQ7rFFt7nZcfSv3/l8Fnhf0KLV8hTbDnjqHvBIATofIU6qRsFGjiRDjaYicTHs37gw9uy2yxC/jTeBYww5LCN5uFHXorEzwXbVZs066GW73WdeE3w6bFlY4IQRgJstImgDZVuLU2x5uvLrQ1hXP/tlXpucylpN0nbLHFHiqMG7ICCf8Pyd9By4RVoflvEUQnMEex2SjW8ZNfraFPq15gfRoz+VtK9j9Zmh3XrFskbwKC8ne90Ei9s7PJowZb+hiEUezzQGx0Ige3jrZhuvCVoAwI5UQ18="
